### ISSUE TITLE
Does this support Swagger 2.0?

### ISSUE THREAD

**Issue by lmaccherone** [bardzusny/swaggerize-restify#5]

**Comment by bardzusny** [comment]
Yes. :)

**Comment by lmaccherone** [comment]
Thanks

**Comment by bardzusny** [comment]
No problem :) basically the functionality is the same as [swaggerize-express](https://github.com/krakenjs/swaggerize-express), so their (more complete and expanded) docs are good reference point for this project as well. Merry Christmas!
